name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn prepublishOnly

      - name: setup test w/ local package install
        run: ./test/setup.sh

      - name: assert lockfile generated for simple project
        run: ./test/run.sh simple
