name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "yarn"
          cache-dependency-path: subdir/package-lock.json
      - run: yarn install --frozen-lockfile
      - run: yarn prepublishOnly

      - name: Generate lockfile for simple project
        working-directory: test/fixtures/simple
        run: node ../../../dist/main.js --pod-version 1.14.3

      - name: Assert result for simple project
        working-directory: test/fixtures/simple
        run: |
          set +e
          cmp Podfile.lock.snapshot Podfile.lock
          if [[ $? -ne 0 ]]; then
            echo "Podfile.lock is not equal to Podfile.lock.snapshot"
            diff -u Podfile.lock.snapshot Podfile.lock
            exit 1
          else
            echo "Lockfiles are equal"
          fi
