name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install

      - name: Generate lockfile for simple project
        working-directory: test/fixtures/simple
        run: bun run ../../../src/main.ts

      - name: Assert result for simple project
        working-directory: test/fixtures/simple
        run: cmp Podfile.lock.snapshot Podfile.lock
